name: Master

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [windows, ubuntu, macos]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Deps
        run: dotnet restore Open.Nat.UnitTests/Open.Nat.Tests.csproj

      - name: Build
        run: dotnet build Open.Nat.UnitTests/Open.Nat.Tests.csproj --configuration Release --no-restore

      - name: Test
        # skip IPv6 tests: https://github.com/actions/runner-images/issues/668
        run: dotnet test Open.Nat.UnitTests/Open.Nat.Tests.csproj --no-restore --verbosity normal --filter TestCategory!=IPv6
